[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
chrono = { version = "0.4.26", features = ["serde"] }
env_logger = "0.10.0"
serde = { version = "1.0.183", features = ["derive"] }
uuid = { version = "1.4.1", features = ["v4"] }
